

import {
  CHOCO_KPI, CHOCO_ALERTS, CHOCO_ACTIVITY, CHOCO_COMPETITORS, CHOCO_REPORTS, CHOCO_SIGNALS, CHOCO_TEAM
} from './choco-data'

import {
  CHOCO_MARKET, CHOCO_NOTIFICATIONS, CHOCO_GRI_DOMAINS, CHOCO_METRICS,
  CHOCO_PRODUCTS, CHOCO_SCENARIOS
} from './choco-data-ext'

export function getDashboardData(email?: string | null) {
  const isChoco = email === 'portal@chocofamily.kz'

  if (isChoco) {
    return {
      KPI: CHOCO_KPI,
      ALERTS: CHOCO_ALERTS,
      ACTIVITY: CHOCO_ACTIVITY,
      COMPETITORS: CHOCO_COMPETITORS,
      REPORTS: CHOCO_REPORTS,
      SIGNALS: CHOCO_SIGNALS,
      TEAM: CHOCO_TEAM,
      MARKET: CHOCO_MARKET,
      NOTIFICATIONS: CHOCO_NOTIFICATIONS,
      GRI_DOMAINS: CHOCO_GRI_DOMAINS,
      METRICS: CHOCO_METRICS,
      PRODUCTS: CHOCO_PRODUCTS,
      SCENARIOS: CHOCO_SCENARIOS,
    }
  }

  return {
    KPI: CHOCO_KPI,
    ALERTS: CHOCO_ALERTS,
    ACTIVITY: CHOCO_ACTIVITY,
    COMPETITORS: CHOCO_COMPETITORS,
    REPORTS: CHOCO_REPORTS,
    SIGNALS: CHOCO_SIGNALS,
    TEAM: CHOCO_TEAM,
    MARKET: CHOCO_MARKET,
    NOTIFICATIONS: CHOCO_NOTIFICATIONS,
    GRI_DOMAINS: CHOCO_GRI_DOMAINS,
    METRICS: CHOCO_METRICS,
    PRODUCTS: CHOCO_PRODUCTS,
    SCENARIOS: CHOCO_SCENARIOS,
  }
}
