/**
 * lib/whatsapp/templates.ts — catalogue of the WhatsApp message templates.
 *
 * Business-initiated WhatsApp messages outside the 24-hour customer service
 * window must use a template approved by Meta (Cloud API › Message templates:
 * https://developers.facebook.com/documentation/business-messaging/whatsapp/templates/overview).
 * Every template below has to be submitted in WhatsApp Manager with exactly
 * this name, category, language (WHATSAPP_TEMPLATE_LANG, default 'ru'), body
 * text and button — the list for the owner is in
 * docs/platform/06-integrations.md («WhatsApp: шаблоны для одобрения»).
 *
 * The code sends only the variables. A mismatch between the approved template
 * and the variables sent here makes Meta reject the message (error 132000
 * family), which the outbox records as a permanent failure.
 *
 * Variable rules (Meta): a text parameter may not contain new lines, tabs or
 * more than four consecutive spaces; a body may not start or end with a
 * variable. sanitizeParam enforces the first rule, the bodies the second.
 *
 * URL buttons are dynamic: the approved URL is `<site>/{{1}}` (site =
 * NEXT_PUBLIC_APP_URL of production), the code sends the path suffix.
 */
import { getSiteUrl } from '@/lib/site-url'

export type TemplateKey = 'digest' | 'expert_notification' | 'report_review' | 'staff_alert' | 'phone_verification'

export interface TemplateDefinition {
  name: TemplateKey
  category: 'UTILITY' | 'AUTHENTICATION'
  /** Body text to submit for approval (AUTHENTICATION: preset by Meta, shown for reference). */
  body: string
  /** Meaning of {{1}}, {{2}}, … in order. */
  variables: string[]
  /** Example values for the submission form. */
  examples: string[]
  button:
    | { type: 'url'; text: string; url: string; example: string }
    | { type: 'copy_code'; text: string }
  /** AUTHENTICATION extras chosen in WhatsApp Manager. */
  auth?: { securityRecommendation: true; codeExpirationMinutes: number }
}

export const WHATSAPP_TEMPLATES: Record<TemplateKey, TemplateDefinition> = {
  digest: {
    name: 'digest',
    category: 'UTILITY',
    body:
      'Сводка CRM AIStart360 на сегодня.\n'
      + 'Напоминаний на сегодня и просроченных: {{1}}.\n'
      + 'Клиентов без контакта больше 30 дней: {{2}}.\n'
      + 'Слабый блок GRI: {{3}}.\n'
      + 'Откройте раздел «Клиенты», чтобы связаться с ними.',
    variables: ['число напоминаний', 'число «спящих» клиентов', 'слабый блок GRI или «нет данных»'],
    examples: ['3', '5', 'Денежная стабильность (2.1)'],
    button: { type: 'url', text: 'Открыть «Клиенты»', url: '{site}/{{1}}', example: 'pulse' },
  },
  expert_notification: {
    name: 'expert_notification',
    category: 'UTILITY',
    body:
      'AIStart360, уведомление эксперту: {{1}}.\n'
      + '{{2}}\n'
      + 'Подробности — в кабинете эксперта.',
    variables: ['событие', 'подробности одной строкой'],
    examples: ['Диагностика завершена', 'Клиент: ТОО Ромашка · Точка А: 64/100'],
    button: { type: 'url', text: 'Открыть кабинет', url: '{site}/{{1}}', example: 'expert' },
  },
  report_review: {
    name: 'report_review',
    category: 'UTILITY',
    body:
      'Отчёт «{{1}}», версия {{2}} от {{3}}, клиент: {{4}}.\n'
      + 'Отчёт ждёт вашей проверки: подтвердите публикацию или отправьте его на доработку.',
    variables: ['название отчёта', 'номер версии', 'дата версии', 'клиент'],
    examples: ['Диагностика бизнеса', '3', '06.10.2026', 'ТОО Ромашка'],
    button: { type: 'url', text: 'Проверить отчёт', url: '{site}/{{1}}', example: 'expert/reports' },
  },
  staff_alert: {
    name: 'staff_alert',
    category: 'UTILITY',
    body:
      'AIStart360, уведомление команде ({{1}}): {{2}}.\n'
      + '{{3}}\n'
      + 'Подробности — в панели GIGA.',
    variables: ['уровень', 'заголовок', 'подробности одной строкой'],
    examples: ['Внимание', 'Агент не справился с задачей', 'Агент: report_builder · Ошибка: timeout'],
    button: { type: 'url', text: 'Открыть в GIGA', url: '{site}/{{1}}', example: 'admin-giga-panel/notifications' },
  },
  phone_verification: {
    name: 'phone_verification',
    category: 'AUTHENTICATION',
    // AUTHENTICATION templates have a fixed body generated by Meta for the
    // chosen language; only the code ({{1}}) is a variable.
    body: '{{1}} — код подтверждения (текст задаёт Meta для шаблонов категории «Аутентификация»).',
    variables: ['6-значный код'],
    examples: ['123456'],
    button: { type: 'copy_code', text: 'Скопировать код' },
    auth: { securityRecommendation: true, codeExpirationMinutes: 10 },
  },
}

/** Meta rejects parameters with new lines, tabs or > 4 consecutive spaces. */
export function sanitizeParam(value: unknown, max = 300, fallback = '—'): string {
  const s = String(value ?? '')
    .replace(/[\r\n\t]+/g, ' · ')
    .replace(/\s{2,}/g, ' ')
    .trim()
  const out = s.length > max ? `${s.slice(0, max - 1).trimEnd()}…` : s
  return out || fallback
}

/** Path suffix for a dynamic URL button: '/admin-giga-panel/x?y=1' → 'admin-giga-panel/x?y=1'. */
export function urlSuffix(path: string | null | undefined, fallback: string): string {
  const raw = String(path ?? '').trim()
  if (!raw || /^https?:\/\//i.test(raw) || /\s/.test(raw)) return fallback
  const s = raw.replace(/^\/+/, '')
  return s.length > 0 && s.length <= 500 ? s : fallback
}

/** What the outbox stores and the sender turns into Cloud API components. */
export interface TemplatePayload {
  template: TemplateKey
  body: string[]
  buttons: Array<{ index: number; text: string }>
  /** Plain text for the staff-only WhatsApp Web bridge fallback. */
  fallbackText: string
}

function render(def: TemplateDefinition, body: string[], link: string | null): string {
  let text = def.body
  body.forEach((v, i) => { text = text.split(`{{${i + 1}}}`).join(v) })
  return link ? `${text}\n${link}` : text
}

function urlPayload(key: TemplateKey, body: string[], suffix: string): TemplatePayload {
  const def = WHATSAPP_TEMPLATES[key]
  return { template: key, body, buttons: [{ index: 0, text: suffix }], fallbackText: render(def, body, getSiteUrl(`/${suffix}`)).slice(0, 4096) }
}

export function digestTemplate(d: { overdue: number; sleeping: number; weakBlock: { label: string; score: number } | null }): TemplatePayload {
  const weak = d.weakBlock ? `${d.weakBlock.label} (${Math.round(d.weakBlock.score * 10) / 10})` : 'нет данных'
  return urlPayload('digest', [String(d.overdue), String(d.sleeping), sanitizeParam(weak, 120)], 'pulse')
}

export function expertNotificationTemplate(n: { title: string; lines: string[]; path?: string | null }): TemplatePayload {
  return urlPayload(
    'expert_notification',
    [sanitizeParam(n.title, 120), sanitizeParam(n.lines.join(' · '), 600, 'без подробностей')],
    urlSuffix(n.path, 'expert'),
  )
}

export function reportReviewTemplate(r: { title: string; version: number | string; date: string; client: string; path?: string | null }): TemplatePayload {
  return urlPayload(
    'report_review',
    [sanitizeParam(r.title, 120), sanitizeParam(String(r.version), 10), sanitizeParam(r.date, 20), sanitizeParam(r.client, 120, 'не указан')],
    urlSuffix(r.path, 'expert/reports'),
  )
}

export function staffAlertTemplate(n: { levelLabel: string; title: string; lines: string[]; path?: string | null }): TemplatePayload {
  return urlPayload(
    'staff_alert',
    [sanitizeParam(n.levelLabel, 40), sanitizeParam(n.title, 160), sanitizeParam(n.lines.join(' · '), 600, 'без подробностей')],
    urlSuffix(n.path, 'admin-giga-panel/notifications'),
  )
}

/** Authentication template: the code goes to the body and to the copy-code button. */
export function phoneVerificationTemplate(code: string): TemplatePayload {
  return {
    template: 'phone_verification',
    body: [code],
    buttons: [{ index: 0, text: code }],
    fallbackText: `Код подтверждения AIStart360: ${code}. Действует 10 минут. Никому не сообщайте этот код.`,
  }
}
